
class CityModel{
  static List<String> cities = [
    "Amsterdam, NL",
    "Athens, GR",
    "Bangkok, TH",
    "Barcelona, ES",
    "Beijing, CN",
    "Berlin, DE",
    "Bogotá, CO",
    "Brussels, BE",
    "Buenos Aires, AR",
    "Cairo, EG",
    "Cape Town, ZA",
    "Chicago, US",
    "Copenhagen, DK",
    "Delhi, IN",
    "Dubai, AE",
    "Dublin, IE",
    "Frankfurt, DE",
    "Hong Kong, CN",
    "Istanbul, TR",
    "Jakarta, ID",
    "Johannesburg, ZA",
    "Karachi, PK",
    "Kuala Lumpur, MY",
    "Kyoto, JP",
    "Lisbon, PT",
    "London, GB",
    "Los Angeles, US",
    "Madrid, ES",
    "Manila, PH",
    "Melbourne, AU",
    "Mexico City, MX",
    "Milan, IT",
    "Montreal, CA",
    "Moscow, RU",
    "Mumbai, IN",
    "Munich, DE",
    "Nairobi, KE",
    "New York, US",
    "Osaka, JP",
    "Oslo, NO",
    "Paris, FR",
    "Prague, CZ",
    "Rio de Janeiro, BR",
    "Riyadh, SA",
    "Rome, IT",
    "San Francisco, US",
    "Santiago, CL",
    "São Paulo, BR",
    "Seoul, KR",
    "Shanghai, CN",
    "Singapore, SG",
    "Stockholm, SE",
    "Sydney, AU",
    "Tokyo, JP",
    "Toronto, CA",
    "Venice, IT",
    "Vienna, AT",
    "Warsaw, PL",
    "Zurich, CH",
  ];




}